sonar.projectKey=devsecops-test-repo
sonar.projectName=Vulnerable DevSecOps Test App
sonar.projectVersion=1.0

# Path to source directories 
sonar.sources=.

# Exclude directories from analysis
sonar.exclusions=**/venv/**,**/*.pyc,**/tests/**

# The language of the project
sonar.language=py

# Encoding of the source code
sonar.sourceEncoding=UTF-8
